---
title: "Open Science Perspectives"
author: "Shuhan Song"
date: "2/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The major goal of open science is to improve the accountability and repeatability of doing science by making the process and outcome of science and research transparent and accessible to all people. Open science is beneficial to researchers because of its accessibility to people. Research and relevant science work made available in open sources were found to be cited more widely, drawing more attention from the media, and attracting more collaborators, employment opportunities, and funding sources (McKiernan et al. 2016). Besides, especially for environmental scientists, the studied system, our environment, is widely if not globally circulated and connected. We cannot fully understand environmental problems without collaborations and contributions from a globally open and accessible community.

Unless what some scientists may concern about, open access journals have higher quality of peer review instead of being low quality and less prestigious (McKiernan et al. 2016). It is in fact possible to publish in journals with high impact factors (IF) values while making it open and accessible by publishing preprints or postprints on open platforms. In addition, some open access journals are cheaper than subscription journals to be published. At very least, publishing self-archiving preprints or postprints can make researchers’ work open without any costs.

However, currently, open science is not fully accessible to everyone (Behlai et al. 2018). Given open science is made available by internet and computer technology, people in areas with limited access to the internet are not fully engaged. Besides, external factors are preventing scientists from making their work accessible. Scientists with stable employment status or in senior positions are more likely to engage the whole team to participate in open science and make more contributions than those at their early career stage. Also, scientists who lack job security or whose institutions lack financial support for publications may fail to make their work open due to financial issues.

Currently, I’m using R and GitHub to store and share my data analysis projects with group mates. However, so far, my work is mostly accessible to classmates. My GitHub repos are not very well organized for other people to navigate. Most repos do not have a clearly explained “readme” to introduce my project. This makes people not familiar with GitHub or data analysis in R hard to understand my work. Besides, though I found twitter to be a good place to learn R, the platform is blocked in China and will make it hard for me to keep updating on R skills when I’m in China. To improve my accessibility as well as the accessibility of my work, I need to adopt better strategies of organizing repos in my GitHub, improving “readme” file for public repos, and engaging with a welcoming and active R learning community when I’m in China. In the long term, I will always seek ways to make my science work accountable and open either through personal blogs or official open access journals.


##### Reference:

McKiernan, E.C. et al. (2016). How open science helps researchers succeed. eLife. 2016; 5: e16800. doi: 10.7554/eLife.16800. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4973366/

Bahlai, C. et al (2018). Open Science Isn't Always Open to All Scientists. American Scientist. https://www.americanscientist.org/article/open-science-isnt-always-open-to-all-scientists
